//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class a2mConnection : DbContext
    {
        public a2mConnection()
            : base("name=a2mConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Business_Status> Business_Status { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Customer_Address> Customer_Address { get; set; }
        public virtual DbSet<Customer_Status> Customer_Status { get; set; }
        public virtual DbSet<Municipality> Municipality { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order_Movements> Order_Movements { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Product_Extender> Product_Extender { get; set; }
        public virtual DbSet<Product_Extender_Group> Product_Extender_Group { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Special_Food_Categories> Special_Food_Categories { get; set; }
        public virtual DbSet<Special_Offers> Special_Offers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
