//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Pk_Admin { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Fk_Municipality { get; set; }
    
        public virtual Municipality Municipality { get; set; }
    }
}
