//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Images
    {
        public int Fk_Business { get; set; }
        public string Image_Name { get; set; }
        public int Pk_Image { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
