//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Status
    {
        public Business_Status()
        {
            this.Businesses = new HashSet<Business>();
        }
    
        public int Pk_Business_Status { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
    }
}
