//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Orders = new HashSet<Orders>();
            this.Special_Offers = new HashSet<Special_Offers>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int Pk_Business { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Alternate_Phone { get; set; }
        public int Fk_Schedule { get; set; }
        public string Address { get; set; }
        public int Fk_Municipality { get; set; }
        public string Email { get; set; }
        public string Webpage { get; set; }
        public Nullable<decimal> Min_Price_For_Shipping { get; set; }
        public bool Allow_Shipping { get; set; }
        public bool Allow_PickUp { get; set; }
        public decimal Shipping_Cost_If_Not_Min_Price { get; set; }
        public bool Allow_Shipping_Not_Enougth_Amount { get; set; }
        public int Fk_Business_Status { get; set; }
        public Nullable<decimal> Max_Order_Price_Allowed { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual Business_Status Business_Status { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Special_Offers> Special_Offers { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
