//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Categories = new HashSet<Category>();
            this.Orders = new HashSet<Order>();
            this.Special_Offers = new HashSet<Special_Offers>();
            this.Business_Images = new HashSet<Business_Images>();
        }
    
        public int Pk_Business { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Alternate_Phone { get; set; }
        public int Fk_Schedule { get; set; }
        public string Address { get; set; }
        public int Fk_Municipality { get; set; }
        public string Email { get; set; }
        public string Webpage { get; set; }
        public Nullable<decimal> Min_Price_For_Shipping { get; set; }
        public bool Allow_Shipping { get; set; }
        public bool Allow_PickUp { get; set; }
        public decimal Shipping_Cost_If_Not_Min_Price { get; set; }
        public bool Allow_Shipping_Not_Enougth_Amount { get; set; }
        public int Fk_Business_Status { get; set; }
        public Nullable<decimal> Max_Order_Price_Allowed { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Password { get; set; }
        public bool Is_A2M { get; set; }
        public bool Has_Pdf { get; set; }
        public Nullable<System.DateTime> Pdf_Last_Update { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Has_DiaryMenu { get; set; }
    
        public virtual Business_Status Business_Status { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Special_Offers> Special_Offers { get; set; }
        public virtual ICollection<Business_Images> Business_Images { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Business_Status Business_Status1 { get; set; }
    }
}
