//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Address
    {
        public int Fk_Address { get; set; }
        public int Fk_Customer { get; set; }
        public string Name { get; set; }
        public bool Is_Default { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public string Floor { get; set; }
        public string Stairs { get; set; }
        public string Letter { get; set; }
        public string Aditional_Data { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
