//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Customer_Address = new HashSet<Customer_Address>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Pk_Customer { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Second_Surname { get; set; }
        public string Phone { get; set; }
        public string Alternate_Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Fk_Customer_Status { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual ICollection<Customer_Address> Customer_Address { get; set; }
        public virtual Customer_Status Customer_Status { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
