//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality_Status
    {
        public Municipality_Status()
        {
            this.Municipalities = new HashSet<Municipality>();
        }
    
        public int Pk_Municipality_Status { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Municipality> Municipalities { get; set; }
    }
}
