//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        public Municipality()
        {
            this.Admins = new HashSet<Admin>();
            this.Businesses = new HashSet<Business>();
        }
    
        public int Pk_Municipality { get; set; }
        public string Name { get; set; }
        public string Postal_Code { get; set; }
        public int Fk_Municipality_Status { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual Municipality_Status Municipality_Status { get; set; }
    }
}
