//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.Order_Movements = new HashSet<Order_Movements>();
        }
    
        public int Pk_Order { get; set; }
        public int Fk_Customer { get; set; }
        public int Fk_Bussiness { get; set; }
        public int Fk_Order_Status { get; set; }
        public int Total_Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Need_Money_Change { get; set; }
        public Nullable<int> What_Change { get; set; }
        public Nullable<int> Vat { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual ICollection<Order_Movements> Order_Movements { get; set; }
        public virtual Order_Status Order_Status { get; set; }
    }
}
