//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Movements
    {
        public int Pk_Order_Movement { get; set; }
        public int Fk_Order { get; set; }
        public System.DateTime Datetime { get; set; }
        public int Fk_Order_Status { get; set; }
    
        public virtual Order_Status Order_Status { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
