//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Pk_Order_Detail { get; set; }
        public int Fk_Order_Product { get; set; }
        public Nullable<int> Fk_Order_Extender { get; set; }
        public int Fk_Order { get; set; }
        public int Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Product_Extender Product_Extender { get; set; }
        public virtual Products Products { get; set; }
    }
}
