//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Extender
    {
        public Product_Extender()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.Special_Offers = new HashSet<Special_Offers>();
        }
    
        public int Pk_Product_Extender { get; set; }
        public string Name { get; set; }
        public int Fk_Product_Extender_Group { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<decimal> Add_Price { get; set; }
        public Nullable<bool> Is_Default { get; set; }
    
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Product_Extender_Group Product_Extender_Group { get; set; }
        public virtual ICollection<Special_Offers> Special_Offers { get; set; }
    }
}
