//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Product_Extender_Group
    {
        public int Fk_Product { get; set; }
        public int Fk_Product_Extender_Group { get; set; }
        public int Pk_Products_Product_Extender_Group { get; set; }
    
        public virtual Product_Extender_Group Product_Extender_Group { get; set; }
        public virtual Product Product { get; set; }
    }
}
