//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Extender_Group
    {
        public Product_Extender_Group()
        {
            this.Product_Extender = new HashSet<Product_Extender>();
            this.Products = new HashSet<Products>();
        }
    
        public int Pk_Product_Extender_Group { get; set; }
        public string Name { get; set; }
        public int Fk_Product { get; set; }
    
        public virtual ICollection<Product_Extender> Product_Extender { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
