//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.Special_Offers = new HashSet<Special_Offers>();
            this.Product_Extender_Group = new HashSet<Product_Extender_Group>();
            this.Special_Food_Categories = new HashSet<Special_Food_Categories>();
        }
    
        public int Pk_Product { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public int Fk_Category { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string Custom_Image { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual ICollection<Special_Offers> Special_Offers { get; set; }
        public virtual ICollection<Product_Extender_Group> Product_Extender_Group { get; set; }
        public virtual ICollection<Special_Food_Categories> Special_Food_Categories { get; set; }
    }
}
