//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2mbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Businesses = new HashSet<Business>();
        }
    
        public int Pk_Schedule { get; set; }
        public string Day_Week { get; set; }
        public string Time_Mask { get; set; }
        public int Fk_Business { get; set; }
    
        public virtual ICollection<Business> Businesses { get; set; }
    }
}
